/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LcYr4RiLR7n
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";

export function AudioDashboard() {
  return (
    <div className="grid w-full lg:min-h-[calc(100vh-70px)] lg:grid-cols-[300px,1fr] gap-4 p-6">
      <div className="border-r bg-gray-100/40 dark:bg-gray-800/40 rounded-lg shadow-lg">
        <div className="flex flex-col gap-4 p-4">
          <h1 className="font-semibold text-lg md:text-2xl">Audio Input</h1>
          <div className="grid w-full items-center gap-2">
            <Label htmlFor="audio-upload">Upload Audio</Label>
            <Input
              aria-label="Upload audio"
              className="border-gray-300 shadow-sm rounded-lg"
              id="audio-upload"
              type="file"
            />
          </div>
          <hr className="my-4" />
        </div>
      </div>
      <div className="flex flex-col gap-4">
        <h1 className="font-semibold text-lg md:text-2xl">Audio Jobs</h1>
        <div className="border shadow-sm rounded-lg">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[80px]">Job ID</TableHead>
                <TableHead className="max-w-[150px]">Audio Title</TableHead>
                <TableHead className="hidden md:table-cell">Status</TableHead>
                <TableHead className="hidden md:table-cell">Duration</TableHead>
                <TableHead>Uploaded</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>001</TableCell>
                <TableCell className="font-medium">Audio 1</TableCell>
                <TableCell className="hidden md:table-cell">
                  <Badge className="py-1 px-2 bg-green-200 text-green-800 rounded-full">
                    Completed
                  </Badge>
                </TableCell>
                <TableCell>3:20</TableCell>
                <TableCell className="hidden md:table-cell">
                  Dec 12, 2023
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>002</TableCell>
                <TableCell className="font-medium">Audio 2</TableCell>
                <TableCell className="hidden md:table-cell">
                  <Badge className="py-1 px-2 bg-yellow-200 text-yellow-800 rounded-full">
                    Processing
                  </Badge>
                </TableCell>
                <TableCell>4:56</TableCell>
                <TableCell className="hidden md:table-cell">
                  Dec 12, 2023
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>003</TableCell>
                <TableCell className="font-medium">Audio 3</TableCell>
                <TableCell className="hidden md:table-cell">
                  <Badge className="py-1 px-2 bg-red-200 text-red-800 rounded-full">
                    Failed
                  </Badge>
                </TableCell>
                <TableCell>2:45</TableCell>
                <TableCell className="hidden md:table-cell">
                  Dec 11, 2023
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  );
}

function MicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  );
}
